#!/bin/bash

echo "🔧 Patch RTC : tampon ICE + flush + vérif socket.emit"
echo "------------------------------------------------------"

TARGET="public/js/rtc-core.js"
PATCH="rtc-core-buffer.patch"
SERVER="server.js"

# 1. Créer le patch ligne par ligne
echo "📦 Création du patch dans $PATCH"
rm -f "$PATCH"
touch "$PATCH"

echo '--- public/js/rtc-core.js.old' >> "$PATCH"
echo '+++ public/js/rtc-core.js' >> "$PATCH"
echo '@@ -10,6 +10,8 @@' >> "$PATCH"
echo ' let localStream = null;' >> "$PATCH"
echo ' let peerConnection = null;' >> "$PATCH"
echo ' let remoteId = null;' >> "$PATCH"
echo ' +let iceBuffer = [];' >> "$PATCH"
echo ' +let partnerSocketId = null;' >> "$PATCH"
echo ' let socket = null;' >> "$PATCH"
echo ' window.lastRTCPartnerId = null;' >> "$PATCH"
echo '' >> "$PATCH"
echo '@@ -20,6 +22,24 @@' >> "$PATCH"
echo '   }' >> "$PATCH"
echo ' };' >> "$PATCH"
echo '' >> "$PATCH"
echo ' +/**' >> "$PATCH"
echo ' + * Envoie un candidat ICE au partenaire.' >> "$PATCH"
echo ' + */' >> "$PATCH"
echo ' +function sendIce(candidate) {' >> "$PATCH"
echo ' +  if (partnerSocketId) {' >> "$PATCH"
echo ' +    socket.emit("ice-candidate", { to: partnerSocketId, candidate });' >> "$PATCH"
echo ' +  } else {' >> "$PATCH"
echo ' +    iceBuffer.push(candidate);' >> "$PATCH"
echo ' +  }' >> "$PATCH"
echo ' +}' >> "$PATCH"
echo '' >> "$PATCH"
echo ' +function flushIceBuffer() {' >> "$PATCH"
echo ' +  if (partnerSocketId && iceBuffer.length > 0) {' >> "$PATCH"
echo ' +    console.log(`[RTC] 🔁 ICE buffer vidé (${iceBuffer.length} candidats).`);' >> "$PATCH"
echo ' +    iceBuffer.forEach(c => socket.emit("ice-candidate", { to: partnerSocketId, candidate: c }));' >> "$PATCH"
echo ' +    iceBuffer = [];' >> "$PATCH"
echo ' +  }' >> "$PATCH"
echo ' +}' >> "$PATCH"
echo '' >> "$PATCH"
echo '@@ -50,7 +70,7 @@' >> "$PATCH"
echo '   pc.onicecandidate = (event) => {' >> "$PATCH"
echo '     if (event.candidate) {' >> "$PATCH"
echo '       console.log(`[RTC] ICE candidat généré.`);' >> "$PATCH"
echo ' -      socket.emit("ice-candidate", { to: remoteId, candidate: event.candidate });' >> "$PATCH"
echo ' +      sendIce(event.candidate);' >> "$PATCH"
echo '     }' >> "$PATCH"
echo '   };' >> "$PATCH"
echo '' >> "$PATCH"
echo '@@ -90,6 +110,8 @@' >> "$PATCH"
echo '     remoteId = partnerId;' >> "$PATCH"
echo '     window.lastRTCPartnerId = partnerId;' >> "$PATCH"
echo '     peerConnection = createPeerConnection(localStream);' >> "$PATCH"
echo ' +    partnerSocketId = partnerId;' >> "$PATCH"
echo ' +    flushIceBuffer();' >> "$PATCH"
echo '     const offer = await peerConnection.createOffer();' >> "$PATCH"
echo '' >> "$PATCH"
echo '@@ -120,6 +142,8 @@' >> "$PATCH"
echo '     remoteId = data.from;' >> "$PATCH"
echo '     window.lastRTCPartnerId = data.from;' >> "$PATCH"
echo '     peerConnection = createPeerConnection(localStream);' >> "$PATCH"
echo ' +    partnerSocketId = data.from;' >> "$PATCH"
echo ' +    flushIceBuffer();' >> "$PATCH"
echo '     await peerConnection.setRemoteDescription(new RTCSessionDescription(data.sdp));' >> "$PATCH"
echo '' >> "$PATCH"
echo '@@ -150,7 +174,13 @@' >> "$PATCH"
echo '   socket = io();' >> "$PATCH"
echo '   socket.on("connect", () => {' >> "$PATCH"
echo '     console.log(`[SOCKET] Connecté (id: ${socket.id}).`);' >> "$PATCH"
echo ' +  });' >> "$PATCH"
echo ' +' >> "$PATCH"
echo ' +  socket.on("partner", (data) => {' >> "$PATCH"
echo ' +    if (data.id) {' >> "$PATCH"
echo ' +      partnerSocketId = data.id;' >> "$PATCH"
echo ' +      flushIceBuffer();' >> "$PATCH"
echo ' +    }' >> "$PATCH"
echo ' +  });' >> "$PATCH"

# 2. Sauvegarde et application
echo "📦 Sauvegarde → $TARGET.old"
cp "$TARGET" "$TARGET.old"

echo "📦 Application du patch"
patch "$TARGET" < "$PATCH"

# 3. Vérification socket.emit("partner")
echo "🔍 Vérification dans $SERVER..."
if grep -q 'socket.emit("partner"' "$SERVER"; then
  echo "✅ socket.emit(\"partner\") déjà présent"
else
  echo "⚠️ socket.emit(\"partner\") absent — à ajouter après le pairing"
fi

echo "✅ Patch terminé."
