name: Deploy to VPS

on:
  push:
      branches: [ main ]
        workflow_dispatch:

        jobs:
          deploy:
              runs-on: ubuntu-latest
                  steps:
                        - name: SSH into VPS and deploy
                                uses: appleboy/ssh-action@v1.0.3
                                        with:
                                                  host: ${{ secrets.VPS_HOST }}
                                                            username: ${{ secrets.VPS_USER }}
                                                                      key: ${{ secrets.VPS_SSH_KEY }}
                                                                                port: ${{ secrets.VPS_PORT || 22 }}
                                                                                          script: |
                                                                                                      set -e
                                                                                                                  cd ~/LegalShuffleCam
                                                                                                                              git fetch origin
                                                                                                                                          git reset --hard origin/main
                                                                                                                                                      npm ci --omit=dev
                                                                                                                                                                  # (re)start with PM2
                                                                                                                                                                              export PORT=3000 NODE_ENV=production
                                                                                                                                                                                          pm2 restart legalshufflecam || pm2 start server.js --name legalshufflecam
                                                                                                                                                                                                      pm2 save
